# Generated by Django 5.0.14 on 2026-08-17 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('value_type', models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('boolean', 'Boolean')], max_length=16)),
                ('aggregation', models.CharField(blank=True, choices=[('sum', 'Sum'), ('last', 'Last'), ('avg', 'Average')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_metric_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetricEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('context', models.JSONField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_entries', to=settings.AUTH_USER_MODEL)),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='metrics.metrictype')),
            ],
            options={
                'verbose_name_plural': 'metric entries',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['owner', 'metric_type', '-recorded_at'], name='metrics_met_owner_i_ae34d0_idx')],
            },
        ),
    ]
