# Generated by Django 5.0.14 on 2026-08-18 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metrictype',
            name='is_computed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metrictype',
            name='value_type',
            field=models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('boolean', 'Boolean'), ('date', 'Date')], max_length=16),
        ),
        migrations.CreateModel(
            name='FormulaDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_key', models.CharField(choices=[('bmi', 'BMI'), ('body_fat_navy', 'Body fat % (Navy method)'), ('tdee_mifflin', 'TDEE (Mifflin-St Jeor)')], max_length=32)),
                ('input_mapping', models.JSONField(help_text="Maps formula variable name (e.g. 'weight_kg') to the input MetricType id it should be read from for the current user.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computed_metric_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formula_definition', to='metrics.metrictype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_formula_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['computed_metric_type__name'],
            },
        ),
        migrations.CreateModel(
            name='MetricThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_bound', models.FloatField(blank=True, null=True)),
                ('upper_bound', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='metrics.metrictype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_thresholds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['metric_type__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='metricthreshold',
            constraint=models.UniqueConstraint(fields=('user', 'metric_type'), name='unique_threshold_per_user_metric_type'),
        ),
    ]
