# Generated by Django 5.0.14 on 2026-08-18 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_favoritemetric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrictype',
            name='value_type',
            field=models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('boolean', 'Boolean'), ('date', 'Date'), ('choice', 'Choice')], max_length=16),
        ),
        migrations.CreateModel(
            name='MetricTypeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=100)),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='metrics.metrictype')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='metrictypechoice',
            constraint=models.UniqueConstraint(fields=('metric_type', 'code'), name='unique_choice_code_per_metric_type'),
        ),
    ]
