# Generated by Django 5.0.14 on 2026-08-19 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0009_metrictype_is_singleton'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricImportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=100)),
                ('separator', models.CharField(max_length=10)),
                ('date_format', models.CharField(max_length=50)),
                ('decimal_separator', models.CharField(default='.', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_settings', to='metrics.metrictype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_import_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='metricimportsettings',
            constraint=models.UniqueConstraint(fields=('user', 'metric_type'), name='unique_import_settings_per_user_metric_type'),
        ),
    ]
