# Generated by Django 5.0.14 on 2026-08-19 07:54, hand-edited to insert a data
# migration between creating DashboardElement and dropping FavoriteMetric —
# see "Dashboard elements" in CLAUDE.md for why FavoriteMetric was replaced.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_favorites_to_dashboard_elements(apps, schema_editor):
    FavoriteMetric = apps.get_model("metrics", "FavoriteMetric")
    DashboardElement = apps.get_model("metrics", "DashboardElement")
    for favorite in FavoriteMetric.objects.all():
        DashboardElement.objects.create(
            user_id=favorite.user_id,
            metric_type_id=favorite.metric_type_id,
            show_chart=True,
            timeframe="all",
            order=favorite.order,
        )


def migrate_dashboard_elements_to_favorites(apps, schema_editor):
    FavoriteMetric = apps.get_model("metrics", "FavoriteMetric")
    DashboardElement = apps.get_model("metrics", "DashboardElement")
    for element in DashboardElement.objects.all():
        FavoriteMetric.objects.create(
            user_id=element.user_id, metric_type_id=element.metric_type_id, order=element.order
        )


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0010_metricimportsettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_chart', models.BooleanField(default=False)),
                ('show_current', models.BooleanField(default=False)),
                ('show_max', models.BooleanField(default=False)),
                ('show_min', models.BooleanField(default=False)),
                ('show_avg', models.BooleanField(default=False)),
                ('timeframe', models.CharField(choices=[('7d', '7 days'), ('30d', '30 days'), ('90d', '90 days'), ('1y', '1 year'), ('3y', '3 years'), ('all', 'All time'), ('custom', 'Custom')], default='30d', max_length=20)),
                ('custom_range_start', models.DateField(blank=True, null=True)),
                ('custom_range_end', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_elements', to='metrics.metrictype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_elements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.RunPython(
            migrate_favorites_to_dashboard_elements, migrate_dashboard_elements_to_favorites
        ),
        migrations.DeleteModel(
            name='FavoriteMetric',
        ),
        migrations.AddConstraint(
            model_name='dashboardelement',
            constraint=models.UniqueConstraint(fields=('user', 'metric_type'), name='unique_dashboard_element_per_user'),
        ),
    ]
