# Generated by Django 5.0.14 on 2026-08-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0011_dashboardelement_delete_favoritemetric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardelement',
            name='show_time_in_range',
            field=models.BooleanField(default=False),
        ),
    ]
