# Generated by Django 5.0.14 on 2026-08-19 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutrientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('macro', 'Macro'), ('micro', 'Micro')], max_length=10)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('own', 'Own'), ('external', 'External')], default='own', max_length=10)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('calories_per_100g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('protein_per_100g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fat_per_100g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodNutrientValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_100g', models.DecimalField(decimal_places=3, max_digits=8)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_values', to='nutrition.fooditem')),
                ('nutrient_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.nutrienttype')),
            ],
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['owner', 'name'], name='nutrition_f_owner_i_65f840_idx'),
        ),
        migrations.AddConstraint(
            model_name='foodnutrientvalue',
            constraint=models.UniqueConstraint(fields=('food_item', 'nutrient_type'), name='unique_nutrient_value_per_food_item'),
        ),
    ]
