# Generated by Django 5.0.14 on 2026-08-20 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_recipeingredient_mealentry_servings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=10)),
                ('quantity_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('servings', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meal_plan_entries', to='nutrition.fooditem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_entries', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meal_plan_entries', to='nutrition.recipe')),
                ('resulting_meal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_plan_entry', to='nutrition.mealentry')),
            ],
            options={
                'verbose_name_plural': 'meal plan entries',
                'ordering': ['date', 'meal_type'],
                'indexes': [models.Index(fields=['owner', 'date'], name='nutrition_m_owner_i_c06897_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mealplanentry',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('food_item__isnull', False), ('recipe__isnull', True)), models.Q(('food_item__isnull', True), ('recipe__isnull', False)), _connector='OR'), name='mealplanentry_exactly_one_of_food_or_recipe'),
        ),
    ]
